// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/oxyno-zeta/s3-proxy/pkg/s3-proxy/s3client (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_Client.go -package=mocks github.com/oxyno-zeta/s3-proxy/pkg/s3-proxy/s3client Client
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	s3client "github.com/oxyno-zeta/s3-proxy/pkg/s3-proxy/s3client"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// DeleteObject mocks base method.
func (m *MockClient) DeleteObject(ctx context.Context, key string) (*s3client.ResultInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", ctx, key)
	ret0, _ := ret[0].(*s3client.ResultInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockClientMockRecorder) DeleteObject(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockClient)(nil).DeleteObject), ctx, key)
}

// GetObject mocks base method.
func (m *MockClient) GetObject(ctx context.Context, input *s3client.GetInput) (*s3client.GetOutput, *s3client.ResultInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, input)
	ret0, _ := ret[0].(*s3client.GetOutput)
	ret1, _ := ret[1].(*s3client.ResultInfo)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetObject indicates an expected call of GetObject.
func (mr *MockClientMockRecorder) GetObject(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockClient)(nil).GetObject), ctx, input)
}

// GetObjectSignedURL mocks base method.
func (m *MockClient) GetObjectSignedURL(ctx context.Context, input *s3client.GetInput, expiration time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectSignedURL", ctx, input, expiration)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectSignedURL indicates an expected call of GetObjectSignedURL.
func (mr *MockClientMockRecorder) GetObjectSignedURL(ctx, input, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectSignedURL", reflect.TypeOf((*MockClient)(nil).GetObjectSignedURL), ctx, input, expiration)
}

// HeadObject mocks base method.
func (m *MockClient) HeadObject(ctx context.Context, key string) (*s3client.HeadOutput, *s3client.ResultInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeadObject", ctx, key)
	ret0, _ := ret[0].(*s3client.HeadOutput)
	ret1, _ := ret[1].(*s3client.ResultInfo)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// HeadObject indicates an expected call of HeadObject.
func (mr *MockClientMockRecorder) HeadObject(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadObject", reflect.TypeOf((*MockClient)(nil).HeadObject), ctx, key)
}

// ListFilesAndDirectories mocks base method.
func (m *MockClient) ListFilesAndDirectories(ctx context.Context, key string) ([]*s3client.ListElementOutput, *s3client.ResultInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFilesAndDirectories", ctx, key)
	ret0, _ := ret[0].([]*s3client.ListElementOutput)
	ret1, _ := ret[1].(*s3client.ResultInfo)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListFilesAndDirectories indicates an expected call of ListFilesAndDirectories.
func (mr *MockClientMockRecorder) ListFilesAndDirectories(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFilesAndDirectories", reflect.TypeOf((*MockClient)(nil).ListFilesAndDirectories), ctx, key)
}

// PutObject mocks base method.
func (m *MockClient) PutObject(ctx context.Context, input *s3client.PutInput) (*s3client.ResultInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", ctx, input)
	ret0, _ := ret[0].(*s3client.ResultInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObject indicates an expected call of PutObject.
func (mr *MockClientMockRecorder) PutObject(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockClient)(nil).PutObject), ctx, input)
}
