#:schema https://mise.jdx.dev/schema/mise.json

[tools]
"node" = "26.7.0"
"npm:oxfmt" = "0.64.0"
pre-commit = '4.6.2'
go = '1.27.1'
golangci-lint = "2.13.1"
# renovate: datasource=github-tags depName=gotestyourself/gotestsum
gotestsum = "1.13.0"
# renovate: datasource=go depName=go.uber.org/mock/mockgen
"go:go.uber.org/mock/mockgen" = "v0.6.0"
# renovate: datasource=go depName=golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment
"go:golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment" = "v0.49.0"
# renovate: datasource=github-tags depName=jmattheis/goverter
"go:github.com/jmattheis/goverter/cmd/goverter" = "v1.9.4"

[hooks]
postinstall = "pre-commit install"
