FROM squidfunk/mkdocs-material:9.5.49

# renovate: datasource=pypi depName=mkdocs-awesome-pages-plugin
ENV MKDOCS_AWESOME_PAGES_PLUGIN_VERSION="2.8.0"

RUN pip install mkdocs-awesome-pages-plugin==${MKDOCS_AWESOME_PAGES_PLUGIN_VERSION}
