// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/oxyno-zeta/s3-proxy/pkg/s3-proxy/response-handler (interfaces: ResponseHandler)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	responsehandler "github.com/oxyno-zeta/s3-proxy/pkg/s3-proxy/response-handler"
)

// MockResponseHandler is a mock of ResponseHandler interface.
type MockResponseHandler struct {
	ctrl     *gomock.Controller
	recorder *MockResponseHandlerMockRecorder
}

// MockResponseHandlerMockRecorder is the mock recorder for MockResponseHandler.
type MockResponseHandlerMockRecorder struct {
	mock *MockResponseHandler
}

// NewMockResponseHandler creates a new mock instance.
func NewMockResponseHandler(ctrl *gomock.Controller) *MockResponseHandler {
	mock := &MockResponseHandler{ctrl: ctrl}
	mock.recorder = &MockResponseHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponseHandler) EXPECT() *MockResponseHandlerMockRecorder {
	return m.recorder
}

// BadRequestError mocks base method.
func (m *MockResponseHandler) BadRequestError(arg0 func(context.Context, string) (string, error), arg1 error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BadRequestError", arg0, arg1)
}

// BadRequestError indicates an expected call of BadRequestError.
func (mr *MockResponseHandlerMockRecorder) BadRequestError(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BadRequestError", reflect.TypeOf((*MockResponseHandler)(nil).BadRequestError), arg0, arg1)
}

// FoldersFilesList mocks base method.
func (m *MockResponseHandler) FoldersFilesList(arg0 func(context.Context, string) (string, error), arg1 []*responsehandler.Entry) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FoldersFilesList", arg0, arg1)
}

// FoldersFilesList indicates an expected call of FoldersFilesList.
func (mr *MockResponseHandlerMockRecorder) FoldersFilesList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FoldersFilesList", reflect.TypeOf((*MockResponseHandler)(nil).FoldersFilesList), arg0, arg1)
}

// ForbiddenError mocks base method.
func (m *MockResponseHandler) ForbiddenError(arg0 func(context.Context, string) (string, error), arg1 error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ForbiddenError", arg0, arg1)
}

// ForbiddenError indicates an expected call of ForbiddenError.
func (mr *MockResponseHandlerMockRecorder) ForbiddenError(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForbiddenError", reflect.TypeOf((*MockResponseHandler)(nil).ForbiddenError), arg0, arg1)
}

// InternalServerError mocks base method.
func (m *MockResponseHandler) InternalServerError(arg0 func(context.Context, string) (string, error), arg1 error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InternalServerError", arg0, arg1)
}

// InternalServerError indicates an expected call of InternalServerError.
func (mr *MockResponseHandlerMockRecorder) InternalServerError(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalServerError", reflect.TypeOf((*MockResponseHandler)(nil).InternalServerError), arg0, arg1)
}

// NoContent mocks base method.
func (m *MockResponseHandler) NoContent() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NoContent")
}

// NoContent indicates an expected call of NoContent.
func (mr *MockResponseHandlerMockRecorder) NoContent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NoContent", reflect.TypeOf((*MockResponseHandler)(nil).NoContent))
}

// NotFoundError mocks base method.
func (m *MockResponseHandler) NotFoundError(arg0 func(context.Context, string) (string, error)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotFoundError", arg0)
}

// NotFoundError indicates an expected call of NotFoundError.
func (mr *MockResponseHandlerMockRecorder) NotFoundError(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotFoundError", reflect.TypeOf((*MockResponseHandler)(nil).NotFoundError), arg0)
}

// NotModified mocks base method.
func (m *MockResponseHandler) NotModified() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotModified")
}

// NotModified indicates an expected call of NotModified.
func (mr *MockResponseHandlerMockRecorder) NotModified() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotModified", reflect.TypeOf((*MockResponseHandler)(nil).NotModified))
}

// PreconditionFailed mocks base method.
func (m *MockResponseHandler) PreconditionFailed() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PreconditionFailed")
}

// PreconditionFailed indicates an expected call of PreconditionFailed.
func (mr *MockResponseHandlerMockRecorder) PreconditionFailed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreconditionFailed", reflect.TypeOf((*MockResponseHandler)(nil).PreconditionFailed))
}

// RedirectWithTrailingSlash mocks base method.
func (m *MockResponseHandler) RedirectWithTrailingSlash() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RedirectWithTrailingSlash")
}

// RedirectWithTrailingSlash indicates an expected call of RedirectWithTrailingSlash.
func (mr *MockResponseHandlerMockRecorder) RedirectWithTrailingSlash() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedirectWithTrailingSlash", reflect.TypeOf((*MockResponseHandler)(nil).RedirectWithTrailingSlash))
}

// StreamFile mocks base method.
func (m *MockResponseHandler) StreamFile(arg0 *responsehandler.StreamInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamFile", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamFile indicates an expected call of StreamFile.
func (mr *MockResponseHandlerMockRecorder) StreamFile(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamFile", reflect.TypeOf((*MockResponseHandler)(nil).StreamFile), arg0)
}

// TargetList mocks base method.
func (m *MockResponseHandler) TargetList() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TargetList")
}

// TargetList indicates an expected call of TargetList.
func (mr *MockResponseHandlerMockRecorder) TargetList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TargetList", reflect.TypeOf((*MockResponseHandler)(nil).TargetList))
}

// UnauthorizedError mocks base method.
func (m *MockResponseHandler) UnauthorizedError(arg0 func(context.Context, string) (string, error), arg1 error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnauthorizedError", arg0, arg1)
}

// UnauthorizedError indicates an expected call of UnauthorizedError.
func (mr *MockResponseHandlerMockRecorder) UnauthorizedError(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnauthorizedError", reflect.TypeOf((*MockResponseHandler)(nil).UnauthorizedError), arg0, arg1)
}

// UpdateRequestAndResponse mocks base method.
func (m *MockResponseHandler) UpdateRequestAndResponse(arg0 *http.Request, arg1 http.ResponseWriter) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateRequestAndResponse", arg0, arg1)
}

// UpdateRequestAndResponse indicates an expected call of UpdateRequestAndResponse.
func (mr *MockResponseHandlerMockRecorder) UpdateRequestAndResponse(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRequestAndResponse", reflect.TypeOf((*MockResponseHandler)(nil).UpdateRequestAndResponse), arg0, arg1)
}
