// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/oxyno-zeta/s3-proxy/pkg/s3-proxy/response-handler (interfaces: ResponseHandler)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_ResponseHandler.go -package=mocks github.com/oxyno-zeta/s3-proxy/pkg/s3-proxy/response-handler ResponseHandler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	models "github.com/oxyno-zeta/s3-proxy/pkg/s3-proxy/response-handler/models"
	gomock "go.uber.org/mock/gomock"
)

// MockResponseHandler is a mock of ResponseHandler interface.
type MockResponseHandler struct {
	ctrl     *gomock.Controller
	recorder *MockResponseHandlerMockRecorder
	isgomock struct{}
}

// MockResponseHandlerMockRecorder is the mock recorder for MockResponseHandler.
type MockResponseHandlerMockRecorder struct {
	mock *MockResponseHandler
}

// NewMockResponseHandler creates a new mock instance.
func NewMockResponseHandler(ctrl *gomock.Controller) *MockResponseHandler {
	mock := &MockResponseHandler{ctrl: ctrl}
	mock.recorder = &MockResponseHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponseHandler) EXPECT() *MockResponseHandlerMockRecorder {
	return m.recorder
}

// BadRequestError mocks base method.
func (m *MockResponseHandler) BadRequestError(loadFileContent func(context.Context, string) (string, error), err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BadRequestError", loadFileContent, err)
}

// BadRequestError indicates an expected call of BadRequestError.
func (mr *MockResponseHandlerMockRecorder) BadRequestError(loadFileContent, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BadRequestError", reflect.TypeOf((*MockResponseHandler)(nil).BadRequestError), loadFileContent, err)
}

// Delete mocks base method.
func (m *MockResponseHandler) Delete(loadFileContent func(context.Context, string) (string, error), input *models.DeleteInput) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", loadFileContent, input)
}

// Delete indicates an expected call of Delete.
func (mr *MockResponseHandlerMockRecorder) Delete(loadFileContent, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockResponseHandler)(nil).Delete), loadFileContent, input)
}

// FoldersFilesList mocks base method.
func (m *MockResponseHandler) FoldersFilesList(loadFileContent func(context.Context, string) (string, error), entries []*models.Entry) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FoldersFilesList", loadFileContent, entries)
}

// FoldersFilesList indicates an expected call of FoldersFilesList.
func (mr *MockResponseHandlerMockRecorder) FoldersFilesList(loadFileContent, entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FoldersFilesList", reflect.TypeOf((*MockResponseHandler)(nil).FoldersFilesList), loadFileContent, entries)
}

// ForbiddenError mocks base method.
func (m *MockResponseHandler) ForbiddenError(loadFileContent func(context.Context, string) (string, error), err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ForbiddenError", loadFileContent, err)
}

// ForbiddenError indicates an expected call of ForbiddenError.
func (mr *MockResponseHandlerMockRecorder) ForbiddenError(loadFileContent, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForbiddenError", reflect.TypeOf((*MockResponseHandler)(nil).ForbiddenError), loadFileContent, err)
}

// GetRequest mocks base method.
func (m *MockResponseHandler) GetRequest() *http.Request {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequest")
	ret0, _ := ret[0].(*http.Request)
	return ret0
}

// GetRequest indicates an expected call of GetRequest.
func (mr *MockResponseHandlerMockRecorder) GetRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequest", reflect.TypeOf((*MockResponseHandler)(nil).GetRequest))
}

// InternalServerError mocks base method.
func (m *MockResponseHandler) InternalServerError(loadFileContent func(context.Context, string) (string, error), err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InternalServerError", loadFileContent, err)
}

// InternalServerError indicates an expected call of InternalServerError.
func (mr *MockResponseHandlerMockRecorder) InternalServerError(loadFileContent, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalServerError", reflect.TypeOf((*MockResponseHandler)(nil).InternalServerError), loadFileContent, err)
}

// NotFoundError mocks base method.
func (m *MockResponseHandler) NotFoundError(loadFileContent func(context.Context, string) (string, error)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotFoundError", loadFileContent)
}

// NotFoundError indicates an expected call of NotFoundError.
func (mr *MockResponseHandlerMockRecorder) NotFoundError(loadFileContent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotFoundError", reflect.TypeOf((*MockResponseHandler)(nil).NotFoundError), loadFileContent)
}

// NotModified mocks base method.
func (m *MockResponseHandler) NotModified() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotModified")
}

// NotModified indicates an expected call of NotModified.
func (mr *MockResponseHandlerMockRecorder) NotModified() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotModified", reflect.TypeOf((*MockResponseHandler)(nil).NotModified))
}

// PreconditionFailed mocks base method.
func (m *MockResponseHandler) PreconditionFailed() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PreconditionFailed")
}

// PreconditionFailed indicates an expected call of PreconditionFailed.
func (mr *MockResponseHandlerMockRecorder) PreconditionFailed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreconditionFailed", reflect.TypeOf((*MockResponseHandler)(nil).PreconditionFailed))
}

// Put mocks base method.
func (m *MockResponseHandler) Put(loadFileContent func(context.Context, string) (string, error), input *models.PutInput) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Put", loadFileContent, input)
}

// Put indicates an expected call of Put.
func (mr *MockResponseHandlerMockRecorder) Put(loadFileContent, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockResponseHandler)(nil).Put), loadFileContent, input)
}

// RedirectTo mocks base method.
func (m *MockResponseHandler) RedirectTo(url string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RedirectTo", url)
}

// RedirectTo indicates an expected call of RedirectTo.
func (mr *MockResponseHandlerMockRecorder) RedirectTo(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedirectTo", reflect.TypeOf((*MockResponseHandler)(nil).RedirectTo), url)
}

// RedirectWithTrailingSlash mocks base method.
func (m *MockResponseHandler) RedirectWithTrailingSlash() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RedirectWithTrailingSlash")
}

// RedirectWithTrailingSlash indicates an expected call of RedirectWithTrailingSlash.
func (mr *MockResponseHandlerMockRecorder) RedirectWithTrailingSlash() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedirectWithTrailingSlash", reflect.TypeOf((*MockResponseHandler)(nil).RedirectWithTrailingSlash))
}

// StreamFile mocks base method.
func (m *MockResponseHandler) StreamFile(loadFileContent func(context.Context, string) (string, error), input *models.StreamInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamFile", loadFileContent, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamFile indicates an expected call of StreamFile.
func (mr *MockResponseHandlerMockRecorder) StreamFile(loadFileContent, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamFile", reflect.TypeOf((*MockResponseHandler)(nil).StreamFile), loadFileContent, input)
}

// TargetList mocks base method.
func (m *MockResponseHandler) TargetList() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TargetList")
}

// TargetList indicates an expected call of TargetList.
func (mr *MockResponseHandlerMockRecorder) TargetList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TargetList", reflect.TypeOf((*MockResponseHandler)(nil).TargetList))
}

// UnauthorizedError mocks base method.
func (m *MockResponseHandler) UnauthorizedError(loadFileContent func(context.Context, string) (string, error), err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnauthorizedError", loadFileContent, err)
}

// UnauthorizedError indicates an expected call of UnauthorizedError.
func (mr *MockResponseHandlerMockRecorder) UnauthorizedError(loadFileContent, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnauthorizedError", reflect.TypeOf((*MockResponseHandler)(nil).UnauthorizedError), loadFileContent, err)
}

// UpdateRequestAndResponse mocks base method.
func (m *MockResponseHandler) UpdateRequestAndResponse(req *http.Request, res http.ResponseWriter) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateRequestAndResponse", req, res)
}

// UpdateRequestAndResponse indicates an expected call of UpdateRequestAndResponse.
func (mr *MockResponseHandlerMockRecorder) UpdateRequestAndResponse(req, res any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRequestAndResponse", reflect.TypeOf((*MockResponseHandler)(nil).UpdateRequestAndResponse), req, res)
}
