// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/oxyno-zeta/s3-proxy/pkg/s3-proxy/bucket (interfaces: Client)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	bucket "github.com/oxyno-zeta/s3-proxy/pkg/s3-proxy/bucket"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockClient) Delete(arg0 context.Context, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", arg0, arg1)
}

// Delete indicates an expected call of Delete.
func (mr *MockClientMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClient)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockClient) Get(arg0 context.Context, arg1 *bucket.GetInput) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Get", arg0, arg1)
}

// Get indicates an expected call of Get.
func (mr *MockClientMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClient)(nil).Get), arg0, arg1)
}

// HandleBadRequest mocks base method.
func (m *MockClient) HandleBadRequest(arg0 context.Context, arg1 error, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleBadRequest", arg0, arg1, arg2)
}

// HandleBadRequest indicates an expected call of HandleBadRequest.
func (mr *MockClientMockRecorder) HandleBadRequest(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleBadRequest", reflect.TypeOf((*MockClient)(nil).HandleBadRequest), arg0, arg1, arg2)
}

// HandleForbidden mocks base method.
func (m *MockClient) HandleForbidden(arg0 context.Context, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleForbidden", arg0, arg1)
}

// HandleForbidden indicates an expected call of HandleForbidden.
func (mr *MockClientMockRecorder) HandleForbidden(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleForbidden", reflect.TypeOf((*MockClient)(nil).HandleForbidden), arg0, arg1)
}

// HandleInternalServerError mocks base method.
func (m *MockClient) HandleInternalServerError(arg0 context.Context, arg1 error, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleInternalServerError", arg0, arg1, arg2)
}

// HandleInternalServerError indicates an expected call of HandleInternalServerError.
func (mr *MockClientMockRecorder) HandleInternalServerError(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleInternalServerError", reflect.TypeOf((*MockClient)(nil).HandleInternalServerError), arg0, arg1, arg2)
}

// HandleNotFound mocks base method.
func (m *MockClient) HandleNotFound(arg0 context.Context, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleNotFound", arg0, arg1)
}

// HandleNotFound indicates an expected call of HandleNotFound.
func (mr *MockClientMockRecorder) HandleNotFound(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleNotFound", reflect.TypeOf((*MockClient)(nil).HandleNotFound), arg0, arg1)
}

// HandleUnauthorized mocks base method.
func (m *MockClient) HandleUnauthorized(arg0 context.Context, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleUnauthorized", arg0, arg1)
}

// HandleUnauthorized indicates an expected call of HandleUnauthorized.
func (mr *MockClientMockRecorder) HandleUnauthorized(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUnauthorized", reflect.TypeOf((*MockClient)(nil).HandleUnauthorized), arg0, arg1)
}

// Put mocks base method.
func (m *MockClient) Put(arg0 context.Context, arg1 *bucket.PutInput) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Put", arg0, arg1)
}

// Put indicates an expected call of Put.
func (mr *MockClientMockRecorder) Put(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockClient)(nil).Put), arg0, arg1)
}
