{
 "title": "S3 Proxy",
 "tags": [ "s3-proxy" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(s3_operations_total, pod)"
   },
   { "name": "server", "label": "Server", "query": "business, internal" },
   {
    "name": "target",
    "label": "Target",
    "query": "label_values(s3_operations_total, target_name)"
   }
  ]
 },
 "panels": [
  { "title": "Service metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All requests durations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_sum{job=\"s3-proxy\",pod=~\"$pod\",server=~\"$server\"})"
    }
   ]
  },
  {
   "title": "All requests size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(http_request_size_bytes_sum{job=\"s3-proxy\",pod=~\"$pod\",server=~\"$server\"})"
    }
   ]
  },
  {
   "title": "All responses size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(http_response_size_bytes_sum{job=\"s3-proxy\",pod=~\"$pod\",server=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Number of request per host",
   "type": "graph",
   "description": "Values are counted by apps. If an app restarts, the count is reset.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"s3-proxy\",pod=~\"$pod\",server=~\"$server\"}) by (host)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  { "title": "S3 Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "List Objects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(s3_operations_total{pod=~\"$pod\",job=\"s3-proxy\",operation=\"list-objects\",target_name=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Get Object",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(s3_operations_total{pod=~\"$pod\",job=\"s3-proxy\",operation=\"get-object\",target_name=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Head Object",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(s3_operations_total{pod=~\"$pod\",job=\"s3-proxy\",operation=\"head-object\",target_name=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Put Object",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(s3_operations_total{pod=~\"$pod\",job=\"s3-proxy\",operation=\"put-object\",target_name=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Delete Object",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(s3_operations_total{pod=~\"$pod\",job=\"s3-proxy\",operation=\"delete-object\",target_name=~\"$target\"})"
    }
   ]
  },
  { "title": "Authentication & Authorization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Authenticated users",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 1, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(authenticated_total{pod=~\"$pod\",job=\"s3-proxy\"}) by (provider_name, provider_type)",
     "legendFormat": "{{ provider_type }} - {{ provider_name }}"
    }
   ]
  },
  {
   "title": "Authorized users",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 11, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(authorized_total{pod=~\"$pod\",job=\"s3-proxy\"}) by (provider_type)",
     "legendFormat": "{{ provider_type }}"
    }
   ]
  }
 ]
}